# ============================================================
# CODVEDA INTERNSHIP | Level 1 | Task 1: Data Cleaning
# Dataset: Iris
# ============================================================

Task 1: Data Cleaning and
Preprocessing

In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns

In [3]:
# Show all column
pd.set_option('display.max_columns', None)

In [4]:
# Load the iris dataset
df_iris = pd.read_csv('iris.csv')

In [5]:
# check the Shape of the dataframe 
print('shape :', df_iris)
# list of col
print("\nColumns:", df_iris.columns.tolist())
# Check first 5 rows of the dataset
print("\nFirst 5 rows:")
display(df_iris.head())
# Check datatypes
print("\nData types:\n", df_iris.dtypes)

shape :      sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

Columns: ['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'species']

First 5 rows:

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

Data types:
 sepal_length    float64
sepal_width     float64
petal_length    float64
petal_width     float64
species          object
dtype: object

In [6]:
# Dataset Snapshot
def dataset_snapshot(df, name="Dataset"):
    # Add a divider line
    print(f" {'=' *50}")
    print(f" {name} Snapshot")
    print(f"{'=' *50}")
   
    # Number of rows
    print(f" Rows : {df.shape[0]}")
    
    # Number of columns
    print(f" Columns : {df.shape[1]}")
    
    # Check for Missing Values
    print(f" Missing : {df.isnull().sum().sum()}")
    
    # Check for Duplicate
    print(f" Duplicates : {df.duplicated().sum()}")
    # check memory usage
    print(f" Memory : {df.memory_usage(deep=True).sum() / 1024:.2f} KB")
    # Checks Data types
    print(f"\nData types:")
    print(df.dtypes)
    # Checks the first few rows
    print(f"\nFirst few rows:")
    display(df.head())
    
dataset_snapshot(df_iris, "Iris")

 ==================================================
 Iris Snapshot
==================================================
 Rows : 150
 Columns : 5
 Missing : 0
 Duplicates : 3
 Memory : 13.21 KB

Data types:
sepal_length    float64
sepal_width     float64
petal_length    float64
petal_width     float64
species          object
dtype: object

First few rows:

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [7]:
# Show the actual duplicate rows
print("Duplicate rows in rae iris.csv:")
display(df_iris[df_iris.duplicated(keep='first')])

Duplicate rows in rae iris.csv:

     sepal_length  sepal_width  petal_length  petal_width    species
34            4.9          3.1           1.5          0.1     setosa
37            4.9          3.1           1.5          0.1     setosa
142           5.8          2.7           5.1          1.9  virginica

In [8]:
# Create a copy of df_iris
df_iris_clean = df_iris.copy()

In [9]:
# Removes deplicates
df_iris_clean = df_iris_clean.drop_duplicates()

# Standardize species column
# remove whitespaces and convert to lower case
df_iris_clean['species'] = df_iris_clean['species'].str.strip().str.lower()

In [10]:
dataset_snapshot(df_iris_clean, "Iris")

 ==================================================
 Iris Snapshot
==================================================
 Rows : 147
 Columns : 5
 Missing : 0
 Duplicates : 0
 Memory : 13.98 KB

Data types:
sepal_length    float64
sepal_width     float64
petal_length    float64
petal_width     float64
species          object
dtype: object

First few rows:

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [11]:
# Save clean iris Dataset as csv
df_iris_clean.to_csv('iris_clean.csv', index=False)